version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "gradle"
    open-pull-requests-limit: 10
    reviewers:
      - "s24407-pj"
    groups:
      gradle-all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 5
    groups:
      docker-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 5
    groups:
      actions-all:
        patterns:
          - "*"
