spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    pl.kacosmetology.scheduler: DEBUG
    org.springframework.security: DEBUG

whatsapp:
  sender: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,hikaricp,caches,env,threaddump,loggers
  endpoint:
    health:
      show-details: always

