ALTER TABLE users ADD COLUMN no_show_count INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN blocked BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE companies ADD COLUMN max_no_shows INT NOT NULL DEFAULT 3;
